server:
  port: 9009

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/cartigo_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
