server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/cartigo_auth?createDatabaseIfNotExist=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: "change-me-to-a-long-secret-change-me-to-a-long-secret"
  expirationMinutes: ${JWT_EXP_MINUTES:60}
#${JWT_SECRET}
#  ${JWT_SECRET:change-me-to-a-long-secret-change-me-to-a-long-secret}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true