server:
  port: 9014

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://mysql:3306/cartigo_cart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
spring:\n  data:\n    redis:\n      host: redis\n      port: 6379
