server:
  port: 9004

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://mysql:3306/cartigo_inventory?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

