server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartigo_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
jwt:
  secret: "change-me-to-a-long-secret-change-me-to-a-long-secret"
razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_SaCFe54BepiPGe}
  key-secret: ${RAZORPAY_KEY_SECRET:hiRi6uXEfHkdUhpGgVJ8tE0M}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
#    hostname: localhost
#    ip-address: 127.0.0.1
    prefer-ip-address: true