server:
  port: 9007

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://mysql:3306/cartigo_review?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

