server:
  port: 8761
spring:
  boot:
    admin:
      client:
        url: http://monitoring-service:9090
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
