server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/cartigo_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true
