services:
  mysql:
    image: mysql:8.4
    container_name: cartigo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - cartigo_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-config-server
    container_name: cartigo-config-server
    volumes:
      - ./config-repo:/config-repo:ro
    ports:
      - "8888:8888"
    depends_on:
        mysql:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  service-registry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-service-registry
    container_name: cartigo-service-registry
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-auth-service
    container_name: cartigo-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-user-service
    container_name: cartigo-user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-product-service
    container_name: cartigo-product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  cartigo-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-category-service
    container_name: cartigo-category-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-inventory-service
    container_name: cartigo-inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8085:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-cart-service
    container_name: cartigo-cart-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8086:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s



  notification-service:
    profiles: ["optional"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-notification-service
    container_name: cartigo-notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
    ports:
      - "8087:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-api-gateway
    container_name: cartigo-api-gateway
    environment:
        SPRING_PROFILES_ACTIVE: docker
    ports:
        - "8080:8080"
    depends_on:
        service-registry:
          condition: service_healthy
#  order-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-order-service
#    container_name: cartigo-order-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9005:9005"
#    depends_on:
#      - mysql
#      - service-registry
#
#  payment-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-payment-service
#    container_name: cartigo-payment-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#      RAZORPAY_KEY_ID: ""
#      RAZORPAY_KEY_SECRET: ""
#      RAZORPAY_WEBHOOK_SECRET: ""
#    ports:
#      - "9006:9006"
#    depends_on:
#      - mysql
#      - service-registry
#
#  review-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-review-service
#    container_name: cartigo-review-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9007:9007"
#    depends_on:
#      - mysql
#      - service-registry
#
#  return-refund-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-return-refund-service
#    container_name: cartigo-return-refund-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9008:9008"
#    depends_on:
#      - mysql
#      - service-registry



volumes:
  cartigo_mysql_data:
