services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:

      # KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # controller quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # protocol mapping
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # controller settings
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # cluster id
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # auto create topics
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_HEAP_OPTS: -Xmx512M -Xms256M
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  mysql:
    image: mysql:8.4
    container_name: cartigo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - cartigo_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-config-server
    container_name: cartigo-config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config-repo:/config-repo:ro
    ports:
      - "8888:8888"
    depends_on:
        mysql:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  service-registry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-service-registry
    container_name: cartigo-service-registry
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-auth-service
    container_name: cartigo-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-user-service
    container_name: cartigo-user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-product-service
    container_name: cartigo-product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  cartigo-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-category-service
    container_name: cartigo-category-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-inventory-service
    container_name: cartigo-inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8085:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-cart-service
    container_name: cartigo-cart-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8086:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s



  notification-service:
    profiles: ["optional"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-notification-service
    container_name: cartigo-notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
    ports:
      - "8087:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-order-service
    container_name: cartigo-order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8088:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-payment-service
    container_name: cartigo-payment-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    ports:
      - "8089:8080"
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: cartigo-api-gateway
    container_name: cartigo-api-gateway
    environment:
        SPRING_PROFILES_ACTIVE: docker
    ports:
        - "8080:8080"
    depends_on:
        service-registry:
          condition: service_healthy

  monitoring-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: monitoring-service
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      config-server:
        condition: service_healthy
      service-registry:
        condition: service_healthy

#
#  review-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-review-service
#    container_name: cartigo-review-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9007:9007"
#    depends_on:
#      - mysql
#      - service-registry
#
#  return-refund-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        SERVICE: cartigo-return-refund-service
#    container_name: cartigo-return-refund-service
#    environment:
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9008:9008"
#    depends_on:
#      - mysql
#      - service-registry



volumes:
  cartigo_mysql_data:
