server:
  port: 8085

spring:
  application:
    name: cartigo-review-service
  datasource:
    url: jdbc:mysql://localhost:3306/cartigo_review_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  security:
    permit-all: true

order:
  service:
    enabled: true
    name: cartigo-order-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
